import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/plugin/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
    "node:fs",
    "node:crypto",
    "node:path",
    "node:os",
    "node:util",
    "fs",
    "crypto",
    "path",
    "os",
    "util",
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
  loader: {
    ".png": "dataurl",
    ".jpg": "dataurl",
    ".jpeg": "dataurl",
    ".svg": "text",
    ".woff": "dataurl",
    ".woff2": "dataurl",
    ".ttf": "dataurl",
    ".css": "text",
    ".wasm": "dataurl",
  },
  // tldraw CSS is imported as text and injected at runtime to avoid sideEffects tree-shaking
  inject: [],
});

import fs from "fs";
import path from "path";

if (prod) {
  await context.rebuild();
  // Append tldraw CSS to styles.css for Obsidian (no iframe, native view needs styles)
  try {
    const tldrawCssPath = path.join("node_modules", "tldraw", "tldraw.css");
    const stylesPath = "styles.css";
    if (fs.existsSync(tldrawCssPath)) {
      const tldrawCss = fs.readFileSync(tldrawCssPath, "utf-8");
      const existing = fs.existsSync(stylesPath) ? fs.readFileSync(stylesPath, "utf-8") : "";
      // Avoid duplicating if already contains tldraw
      if (!existing.includes("tl-canvas")) {
        fs.writeFileSync(stylesPath, existing + "\n/* tldraw */\n" + tldrawCss);
        console.log("✓ tldraw.css appended to styles.css");
      }
    }
  } catch (e) {
    console.warn("Could not append tldraw.css", e);
  }
  // Copy Quran JSON to plugin root for vault fallback (Obsidian has no /public server)
  try {
    const srcJson = path.join("public", "qpc-hafs-word-by-word.json");
    const destJson = path.join(".", "qpc-hafs-word-by-word.json");
    if (fs.existsSync(srcJson) && !fs.existsSync(destJson)) {
      fs.copyFileSync(srcJson, destJson);
      console.log("✓ qpc-hafs-word-by-word.json copied to plugin root for Obsidian vault fallback");
    } else if (fs.existsSync(srcJson)) {
      // Update if source newer
      const srcStat = fs.statSync(srcJson);
      const destStat = fs.existsSync(destJson) ? fs.statSync(destJson) : null;
      if (!destStat || srcStat.mtimeMs > destStat.mtimeMs) {
        fs.copyFileSync(srcJson, destJson);
        console.log("✓ qpc-hafs-word-by-word.json updated at plugin root");
      }
    }
  } catch (e) {
    console.warn("Could not copy quran JSON", e);
  }
  process.exit(0);
} else {
  await context.watch();
}
