import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/plugin/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
    "node:fs",
    "node:crypto",
    "node:path",
    "node:os",
    "node:util",
    "fs",
    "crypto",
    "path",
    "os",
    "util",
  ],
  format: "cjs",
  target: "es2018",
  // Obsidian Mobile's WebView can load React itself, but its bundled module
  // loader does not reliably preserve the lazy react/jsx-runtime bindings.
  // Use the classic transform for plugin-owned TSX so views call the already
  // bundled React.createElement API directly. The web app keeps tsconfig's
  // automatic JSX transform via the plugin-only tsconfig.
  tsconfig: "tsconfig.plugin.json",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  define: {
    "process.env.NODE_ENV": prod ? '"production"' : '"development"',
  },
  loader: {
    ".png": "dataurl",
    ".jpg": "dataurl",
    ".jpeg": "dataurl",
    ".svg": "text",
    ".woff": "dataurl",
    ".woff2": "dataurl",
    ".ttf": "dataurl",
    ".css": "text",
    ".wasm": "dataurl",
  },
  // tldraw CSS is imported as text and injected at runtime to avoid sideEffects tree-shaking
  inject: [],
});

import fs from "fs";
import path from "path";

if (prod) {
  await context.rebuild();
  // Append tldraw CSS to styles.css for Obsidian (no iframe, native view needs styles)
  try {
    const tldrawCssPath = path.join("node_modules", "tldraw", "tldraw.css");
    const stylesPath = "styles.css";
    if (fs.existsSync(tldrawCssPath)) {
      const tldrawCss = fs.readFileSync(tldrawCssPath, "utf-8");
      const existing = fs.existsSync(stylesPath) ? fs.readFileSync(stylesPath, "utf-8") : "";
      // Avoid duplicating if already contains tldraw
      if (!existing.includes("tl-canvas")) {
        fs.writeFileSync(stylesPath, existing + "\n/* tldraw */\n" + tldrawCss);
        console.log("✓ tldraw.css appended to styles.css");
      }
    }
  } catch (e) {
    console.warn("Could not append tldraw.css", e);
  }
  // Copy Quran JSON to plugin root for vault fallback (Obsidian has no /public server)
  try {
    const srcJson = path.join("public", "qpc-hafs-word-by-word.json");
    const destJson = path.join(".", "qpc-hafs-word-by-word.json");
    if (fs.existsSync(srcJson) && !fs.existsSync(destJson)) {
      fs.copyFileSync(srcJson, destJson);
      console.log("✓ qpc-hafs-word-by-word.json copied to plugin root for Obsidian vault fallback");
    } else if (fs.existsSync(srcJson)) {
      // Update if source newer
      const srcStat = fs.statSync(srcJson);
      const destStat = fs.existsSync(destJson) ? fs.statSync(destJson) : null;
      if (!destStat || srcStat.mtimeMs > destStat.mtimeMs) {
        fs.copyFileSync(srcJson, destJson);
        console.log("✓ qpc-hafs-word-by-word.json updated at plugin root");
      }
    }
  } catch (e) {
    console.warn("Could not copy quran JSON", e);
  }
    // Copy sql.js wasm to plugin root for Obsidian offline packaging (the plugin
  // has no /public server and may be offline, so the Anki export reads the
  // wasm via the vault adapter instead of /sql-wasm.wasm or CDN)
  try {
    const srcWasm = path.join("public", "sql-wasm.wasm");
    const destWasm = path.join(".", "sql-wasm.wasm");
    if (fs.existsSync(srcWasm)) {
      const srcStat = fs.statSync(srcWasm);
      const destStat = fs.existsSync(destWasm) ? fs.statSync(destWasm) : null;
      if (!destStat || srcStat.mtimeMs > destStat.mtimeMs || srcStat.size !== destStat.size) {
        fs.copyFileSync(srcWasm, destWasm);
        console.log("✓ sql-wasm.wasm copied to plugin root for Obsidian offline Anki packaging");
      }
    }
  } catch (e) {
    console.warn("Could not copy sql-wasm.wasm", e);
  }
  // No premade data: Anki Deck is vault-only (users share mindmaps/splits/docs directly).  // Copy recitations JSONs to plugin folder for Obsidian offline fallback (audio player needs surah.json/segments.json)
  // The vault's public/recitations already exists, but plugin folder (.obsidian/plugins/quran-life) is what adapter reads via ".obsidian/plugins/quran-life/..." — ensure it's there
  try {
    const srcRecitations = path.join("public", "recitations");
    if (fs.existsSync(srcRecitations)) {
      const destChoices = [
        path.join(".obsidian", "plugins", "quran-life", "recitations"),
        path.join(".obsidian", "plugins", "quran-life", "public", "recitations"),
      ];
      for (const dest of destChoices) {
        try {
          if (fs.cpSync) {
            fs.cpSync(srcRecitations, dest, { recursive: true, force: true });
          } else {
            // fallback manual copy
            const copyRecursive = (src, dest) => {
              if (!fs.existsSync(dest)) fs.mkdirSync(dest, { recursive: true });
              for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
                const s = path.join(src, entry.name);
                const d = path.join(dest, entry.name);
                if (entry.isDirectory()) copyRecursive(s, d);
                else if (entry.name.endsWith(".json")) {
                  if (!fs.existsSync(d) || fs.statSync(s).mtimeMs > fs.statSync(d).mtimeMs) fs.copyFileSync(s, d);
                }
              }
            };
            copyRecursive(srcRecitations, dest);
          }
          console.log(`✓ recitations JSONs copied to ${dest} for Obsidian audio fallback`);
        } catch (e) {
          console.warn(`Could not copy recitations to ${dest}`, e);
        }
      }
      // Also ensure plugin root recitations for direct adapter read ".obsidian/plugins/quran-life/..." already covered, plus copy to ./recitations for completeness
      try {
        const destRootRecitations = path.join(".", "recitations");
        if (!fs.existsSync(destRootRecitations)) {
          if (fs.cpSync) fs.cpSync(srcRecitations, destRootRecitations, { recursive: true, force: true });
          console.log("✓ recitations copied to ./recitations");
        }
      } catch {}
    }
  } catch (e) {
    console.warn("Could not copy recitations", e);
  }
  await context.dispose();
  process.exit(0);
} else {
  await context.watch();
}
