import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { readFileSync } from "fs";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const __dirname = decodeURI(new URL('.', import.meta.url).pathname);
const TLDRAW_VERSION = (() => {
    const json = JSON.parse(readFileSync(`${__dirname}node_modules/tldraw/package.json`));
    return json.version;
})();

try {
    const context = await esbuild.context({
        banner: {
            js: banner,
        },
        entryPoints: ["src/main.ts", "src/styles.css"],
        bundle: true,
        external: [
            "obsidian",
            "electron",
            "@codemirror/autocomplete",
            "@codemirror/collab",
            "@codemirror/commands",
            "@codemirror/language",
            "@codemirror/lint",
            "@codemirror/search",
            "@codemirror/state",
            "@codemirror/view",
            "@lezer/common",
            "@lezer/highlight",
            "@lezer/lr",
            ...builtins,
        ],
        format: "cjs",
        target: "es2023",
        logLevel: "info",
        sourcemap: false,
        treeShaking: true,
        loader: {
            ".js": "jsx",
            ".woff2": "dataurl",
            ".woff": "dataurl",
            ".svg": "file",
            ".png": "file",
            ".json": "file",
        },
        outdir: ".",
        define: {
            "TLDRAW_COMPONENT_LOGGING": "false",
            "MARKDOWN_POST_PROCESSING_LOGGING": "false",
            "TLDRAW_VERSION": `"${TLDRAW_VERSION}"`,
        }
    });

    await context.rebuild();
    console.log("Build success");
    process.exit(0);
} catch (e) {
    console.error("Build failed");
    if (e.errors) {
        e.errors.forEach(err => {
            console.error(`Error: ${err.text}`);
            if (err.location) {
                console.error(`  at ${err.location.file}:${err.location.line}:${err.location.column}`);
                console.error(`  ${err.location.lineText}`);
            }
        });
    } else {
        console.error(e);
    }
    process.exit(1);
}
